### ISSUE TITLE
Plugin "hyperline" failed to load (Could not find module /hyper/component)

### ISSUE THREAD

**Issue by AtomicCoding** [Hyperline/hyperline#140] opened 2017-12-15 21:39 UTC
After installing Hyperline, this error above is given and weird scrollbars show up on Hyper.
![screen shot 2017-12-15 at 1 37 30 pm](https://user-images.githubusercontent.com/25597810/34061474-63f7ee16-e19d-11e7-8d4f-3ce58a7fe673.png)

**Comment by snorwin** [comment] 2017-12-17 18:08
+1

**Comment by breferrari** [comment] 2017-12-18 16:37
Also happening to me, fresh install

**Comment by stdavis** [comment] 2017-12-19 17:34
I'm having the same issue as well. Here's the output from the dev tools:
![image](https://user-images.githubusercontent.com/1326248/34170445-1a33c35a-e4a8-11e7-98ab-fc1882f28a52.png)
Maybe you are missing a dependency reference in `package.json`?

**Comment by Brhernann** [comment] 2017-12-20 14:55
some solution?

**Comment by Malagari** [comment] 2017-12-23 04:17
First time using Hyper and having the same issue.  Glad to see it's not just me.

**Comment by krzema12** [comment] 2017-12-27 11:36
A duplicate of #134. Here's a mitigation to get it working quickly: add `prop-types` plugin:

```
  plugins: [
    'hyperline',
    'prop-types', # Needed by hyperline. Temporarily adding it here, until it's fixed properly in hyperline.
  ],
```

**Comment by fiso** [comment] 2017-12-29 11:01
Yeah me too.

**Comment by elliotd123** [comment] 2017-12-29 13:25
Going to ~/.hyper_plugins and:

`npm install prop-types`

Worked for me. However, it still complains about react.

**Comment by ryuheechul** [comment] 2017-12-30 07:59
I had the same issue and now it works for me

#### Here is what I think it was why
I think it's because of the old versions of npm and node.

#### Here is what I did to make it work
1. upgrade `node` and `npm` to latest version (mine is v9.3.0 for node and 5.6.0 for npm)
2. `cd ~/.hyper_plugins && rm -rf node_modules && npm install`
3. quit and re-launch hyper

**Comment by tehp** [comment] 2017-12-31 23:40
Did not work for me @ryuheechul.
Only "fix" I could find is using a previous version: `hyperline#0.6.1`.

**Comment by AndKenneth** [comment] 2018-01-05 10:50
adding `prop-types` to the plugins section hyper config file fixed this for me. I also installed it via NPM globally (as my first attempt to fix) but I'm not sure if that matters.

**Closed** 2018-03-06 20:09 UTC

**Comment by tehp** [comment] 2018-03-07 21:58
Is this fixed? Why is the issue closed?

**Comment by keremcankabadayi** [comment] 2018-03-07 22:03
<img width="1259" alt="screenshot at mar 08 01-02-00" src="https://user-images.githubusercontent.com/23381187/37120787-698f40e4-226c-11e8-890b-ee85e16817c1.png">

not fixed. line is working perfectly but i get error when i start the hyper

**Comment by tsaiDavid** [comment] 2018-03-15 19:32
My line shows up (albeit with padding issues) and I get the following issue:

```
Plugin error!
Plugin "hyperline" failed to load (Cannot find module 'react')
```

I tried removing the `package-lock.json` as some had suggested and reinstalling. The only other packages I have are:

`hyper-blink` and `hyperterm-base-16-ocean`

**Comment by mwdiers** [comment] 2018-03-16 17:23
I just installed today. This is still a problem. However, this worked for me:

`cd ~/.hyper_plugins && rm -rf node_modules && npm install`

Followed by a full-reload.

**Comment by RyosukeCla** [comment] 2018-04-05 02:53
This isnt fixed.

- Hyper 1.4.8 (stable)

**Comment by kondr1** [comment] 2018-04-10 11:15
Same problem.  @NickTikhonov  Why you closed this issue?

**Comment by Brhernann** [comment] 2018-04-10 19:06
some solution?

2018-04-10 8:15 GMT-03:00 Konstantin Kondr <notifications@github.com>:

**Comment by tehp** [comment] 2018-04-11 01:57
Seems that the plugin developers are inactive. 
Best bet is to probably just stick with `hyperline#0.6.1`.

**Comment by mucanyu** [comment] 2018-09-21 11:20
It's not fixed yet. Still facing same issue.

**Comment by justinschier** [comment] 2018-11-09 21:51
Still seeing this issue today with a new Hyper and hyperline install.
